### PR TITLE
add course container & course card

### PR DESCRIPTION
**Pull request by ahmed-salah77**

### CODE REVIEW

**Comment by ahmed-salah77** [comment]
I have some problems to access the tasks sheet 
so I can't update any tasks there until fix this problem 

thanks,

**Comment by AhmedMorgan** [comment]
Hi Ahmed, I have some comments on your code.
- use functional component instead of class component.
- remove the unused imports.
- remove console.log before you commit your code.
- avoid using let. you can use const instead if the data will not be changed.
- always add alter to image tag.
- the app should run without any warnings.
- you created a react project inside a react project and the node modules are uploaded also and this is not accepted.
- don't use index.js. just include your code to app.js.
- the courses are not wraped so it is not responsive on smaller screens.

**Comment by ahmed-salah77** [comment]
when I delete index.js it give me error when start the app

**Comment by AhmedMorgan** [comment]
> when I delete index.js it give me error when start the app

I meant to keep it as it is and add your code to App.js, not to index.js

**Pull request merged**
